name: 'jaffle_shop'
config-version: 2
version: '0.1'
dbt-cloud:
    project-id: 70403103921046

profile: 'jaffle_shop'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

seeds:
  jaffle_shop:
    +schema: RAW

models:
  jaffle_shop:
      marts:
        core:
          +materialized: table
      staging:
        +materialized: view